server:
  port: 8082

spring:
  application:
    name: user-service

  # Liquibase Configuration
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    url: jdbc:postgresql://localhost:5442/ott_db
    user: admin
    password: 123456789
    driver-class-name: org.postgresql.Driver

  # R2DBC (PostgresSQL)
  r2dbc:
    host: localhost
    port: 5442
    database: ott_db
    url: r2dbc:postgresql://${spring.r2dbc.host}:${spring.r2dbc.port}/${spring.r2dbc.database}
    username: admin
    password: 123456789

  #Jooq Configuration
  jooq:
    sql-dialect: POSTGRES

  # Redis Configuration
  data:
    redis:
      host: localhost
      port: 6079
      timeout: 60000
      lettuce:
        pool:
          enabled: true
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: 5000ms

# AWS SDK configurations
aws:
  cognito:
    region: us-east-2
    userPoolId: us-east-2_5zEkiuvSQ
    clientId: 77n8pfpllrccdrukrt5cck3t75

# Logging configurations
logging:
  level:
    org.springframework.data.redis: DEBUG